### ISSUE TITLE
Implement a build system

### ISSUE THREAD

**Issue by MikhailZex** [MikhailZex/Proton#7]
### Tasks:

- [ ] **Supported OS's**: Which OS's will be supported? (Win, Linux, Max)

- [ ] **Build System**: Should we use existing build systems or create an brand-new one?

- [ ] **Configurability**: How configurable should the app-build system be? Should it even be configurable?
